name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches: 
        - main  # Runs the action on every push to the main branch
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for the build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
              node-version: '20'
              registry-url: 'https://registry.npmjs.org'
      # Step 3: Navigate to the frontend folder
      - name: Change directory to frontend
        run: cd frontend

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the Vite app
      - name: Build Vite app
        run: npm run build  # This creates the build in the 'dist' folder inside 'frontend'

      # Step 6: Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 7: Upload the build output to GitHub Pages
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist'  # Path to the 'dist' folder inside 'frontend'

      # Step 8: Deploy the built app to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
